name: FileFox Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

# ------------------ BUILD + TEST ------------------
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test --configuration Release --no-build

    - name: Vulnerable packages scan
      run: dotnet list package --vulnerable --include-transitive


# ------------------ CODEQL ------------------
  codeql:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: csharp
        build-mode: autobuild

    - name: Build for CodeQL
      run: dotnet build --configuration Release --no-restore

    - name: Analyze
      uses: github/codeql-action/analyze@v4


# ---------------- INTEGRATION TESTS ----------------
    - name: Integration tests
      run: API_URL=http://localhost:8080 dotnet test FileFox_Backend.Tests --filter "Category=Integration"


# ---------------- ARTIFACTS ----------------
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage
        path: "**/TestResults/**/coverage.cobertura.xml"